[versions]
# https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm
kotlin = "2.2.21"
# https://github.com/Kotlin/kotlinx-io
kotlinx-io= "0.8.0"
# https://github.com/vanniktech/gradle-maven-publish-plugin
publish = "0.35.0"
# https://github.com/Kotlin/dokka
dokka = "2.1.0"
# https://github.com/willowtreeapps/assertk
assertk = "0.28.1"

[libraries]
gradle-kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish" }
gradle-dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
pubhish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
